"""add table user

Revision ID: 73cb3f39efc8
Revises: 5def2a97d835
Create Date: 2022-10-05 22:58:52.185976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73cb3f39efc8'
down_revision = '5def2a97d835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_authenticated')
    # ### end Alembic commands ###
