"""add table

Revision ID: d663aba6cc21
Revises: 33d7f221a147
Create Date: 2022-08-26 01:36:28.036540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd663aba6cc21'
down_revision = '33d7f221a147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xmin2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xmin2')
    # ### end Alembic commands ###
